project_id = "dkjkuxbadylsquvrclnk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["https://dkjkuxbadylsquvrclnk.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true

[functions.scrape-practo-doctors]
verify_jwt = false

[functions.admin-doctors]
verify_jwt = false